# Generated by Django 3.0.7 on 2020-06-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200617_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='semester',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('Core', 'Core'), ('Optional', 'Optional'), ('GEC', 'GEC'), ('Elective', 'Elective')], default='Core', max_length=9),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester_type',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('Winter semester', 'Winter semester')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='GPA',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
