# Generated by Django 3.0.7 on 2020-06-25 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200617_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_code']},
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['plan_code']},
        ),
        migrations.AlterModelOptions(
            name='programsemester',
            options={'ordering': ['plan_code']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id']},
        ),
        migrations.AlterModelOptions(
            name='studentcgpa',
            options={'ordering': ['student_id']},
        ),
        migrations.AlterModelOptions(
            name='studentcourse',
            options={'ordering': ['student_id']},
        ),
        migrations.AddField(
            model_name='programme',
            name='overall_program_credits',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='programsemester',
            name='overall_semester',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='semesters_passed',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='studentcgpa',
            name='CGPA',
            field=models.FloatField(default=2.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='GPA',
            field=models.FloatField(blank=True, default=2.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='course_grade',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.DeleteModel(
            name='StudentProgram',
        ),
    ]
