# Generated by Django 3.0.7 on 2020-06-25 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200625_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercourses', to='accounts.Student'),
        ),
    ]
