# Generated by Django 3.0.7 on 2020-06-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mycourse', to='accounts.Course'),
        ),
    ]
