# Generated by Django 3.0.7 on 2020-06-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200626_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='programme',
            field=models.ManyToManyField(to='accounts.Programme'),
        ),
    ]
