# Generated by Django 3.0.7 on 2020-07-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_course_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PlanCourse_course_code', to='accounts.Course')),
                ('plan_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progCourse_planCode', to='accounts.Programme')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentCGPA',
        ),
    ]
